export declare const MIN_LENGTH_FOR_NSN = 2;
export declare const MAX_LENGTH_FOR_NSN = 17;
export declare const MAX_LENGTH_COUNTRY_CODE = 3;
export declare const VALID_DIGITS = "0-9";
export declare const VALID_PUNCTUATION = "-/.()~ ";
export declare const PLUS_CHARS = "+";
export declare const NON_FIXED_LINE_PHONE_TYPES: readonly ["mobile", "premiumRate", "tollFree", "sharedCost", "voip", "personalNumber", "pager", "uan", "voicemail"];
export declare const FIRST_GROUP_ONLY_PREFIX_PATTERN: RegExp;
export declare const PHONE_NUMBER_TYPES: readonly ["premiumRate", "tollFree", "sharedCost", "voip", "personalNumber", "pager", "uan", "voicemail", "fixedLine", "mobile"];
export declare const MAX_INPUT_STRING_LENGTH = 250;
export declare const CALLING_CODE_REG_EXP: RegExp;
export declare const DEFAULT_EXT_PREFIX = " ext. ";
export declare const RFC3966_EXTN_PREFIX = ";ext=";
